# Generated by Django 6.0.1 on 2026-01-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
