# Generated by Django 6.0.1 on 2026-01-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_bookingschedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Court',
            new_name='TennisClub',
        ),
        migrations.DeleteModel(
            name='BookingSchedule',
        ),
    ]
