# Generated by Django 6.0.1 on 2026-01-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_rename_court_tennisclub_delete_bookingschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='tennisclub',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
