# Generated by Django 6.0.1 on 2026-01-27 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_tennisclub_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('taken', models.IntegerField(default=0)),
                ('TennisClub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.tennisclub')),
            ],
        ),
    ]
