# Generated by Django 6.0.1 on 2026-01-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_slotavailability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slotavailability',
            unique_together={('TennisClub', 'date', 'time')},
        ),
    ]
