# Generated by Django 6.0.1 on 2026-01-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_alter_slotavailability_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennisclub',
            name='quantity',
            field=models.IntegerField(default=3),
        ),
    ]
