# Generated by Django 6.0.1 on 2026-01-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_alter_tennisclub_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotavailability',
            name='taken',
            field=models.IntegerField(default=1),
        ),
    ]
