# Generated by Django 6.0.1 on 2026-02-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_alter_slotavailability_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='tennisclub',
            name='image_hover1',
            field=models.ImageField(blank=True, upload_to='tennis_clubs/'),
        ),
        migrations.AddField(
            model_name='tennisclub',
            name='image_hover2',
            field=models.ImageField(blank=True, upload_to='tennis_clubs/'),
        ),
        migrations.AddField(
            model_name='tennisclub',
            name='image_main',
            field=models.ImageField(blank=True, upload_to='tennis_clubs/'),
        ),
    ]
